 const data=[{name:"Israel",dail_code:"+972",code:"IL", flag: './assets/svgs/il.svg'},
{name:"Afghanistan",dail_code:"+93",code:"AF", flag: require('./assets/svgs/af.svg')},
{name:"Albania",dail_code:"+355",code:"AL", flag: require('./assets/svgs/al.svg')},
{name:"Algeria",dail_code:"+213",code:"DZ", flag: require('./assets/svgs/dz.svg')},
{name:"AmericanSamoa",dail_code:"+1 684",code:"AS", flag: require('./assets/svgs/as.svg')},
{name:"Andorra",dail_code:"+376",code:"AD", flag: require('./assets/svgs/ad.svg')},
{name:"Angola",dail_code:"+244",code:"AO", flag: require('./assets/svgs/ao.svg')},
{name:"Anguilla",dail_code:"+1 264",code:"AI", flag: require('./assets/svgs/ai.svg')},
{name:"Antigua and Barbuda",dail_code:"+1268",code:"AG", flag: require('./assets/svgs/ag.svg')},
{name:"Argentina",dail_code:"+54",code:"AR", flag: require('./assets/svgs/ar.svg')},
{name:"Armenia",dail_code:"+374",code:"AM", flag: require('./assets/svgs/am.svg')},
{name:"Aruba",dail_code:"+297",code:"AW", flag: require('./assets/svgs/aw.svg')},
{name:"Australia",dail_code:"+61",code:"AU", flag: require('./assets/svgs/au.svg')},
{name:"Austria",dail_code:"+43",code:"AT", flag: require('./assets/svgs/at.svg')},
{name:"Azerbaijan",dail_code:"+994",code:"AZ", flag: require('./assets/svgs/az.svg')},
{name:"Bahamas",dail_code:"+1 242",code:"BS", flag: require('./assets/svgs/bs.svg')},
{name:"Bahrain",dail_code:"+973",code:"BH", flag: require('./assets/svgs/bh.svg')},
{name:"Bangladesh",dail_code:"+880",code:"BD", flag: require('./assets/svgs/bd.svg')},
{name:"Barbados",dail_code:"+1 246",code:"BB", flag: require('./assets/svgs/bb.svg')},
{name:"Belarus",dail_code:"+375",code:"BY", flag: require('./assets/svgs/by.svg')},
{name:"Belgium",dail_code:"+32",code:"BE", flag: require('./assets/svgs/be.svg')},
{name:"Belize",dail_code:"+501",code:"BZ", flag: require('./assets/svgs/bz.svg')},
{name:"Benin",dail_code:"+229",code:"BJ", flag: require('./assets/svgs/bj.svg')},
{name:"Bermuda",dail_code:"+1 441",code:"BM", flag: require('./assets/svgs/bm.svg')},
{name:"Bhutan",dail_code:"+975",code:"BT", flag: require('./assets/svgs/bt.svg')},
{name:"Bosnia and Herzegovina",dail_code:"+387",code:"BA", flag: require('./assets/svgs/ba.svg')},
{name:"Botswana",dail_code:"+267",code:"BW", flag: require('./assets/svgs/bw.svg')},
{name:"Brazil",dail_code:"+55",code:"BR", flag: require('./assets/svgs/us.svg')},
{name:"British Indian Ocean Territory",dail_code:"+246",code:"IO", flag: require('./assets/svgs/us.svg')},
{name:"Bulgaria",dail_code:"+359",code:"BG", flag: require('./assets/svgs/us.svg')},
{name:"Burkina Faso",dail_code:"+226",code:"BF", flag: require('./assets/svgs/us.svg')},
{name:"Burundi",dail_code:"+257",code:"BI", flag: require('./assets/svgs/us.svg')},
{name:"Cambodia",dail_code:"+855",code:"KH", flag: require('./assets/svgs/us.svg')},
{name:"Cameroon",dail_code:"+237",code:"CM", flag: require('./assets/svgs/us.svg')},
{name:"Canada",dail_code:"+1",code:"CA", flag: require('./assets/svgs/us.svg')},
{name:"Cape Verde",dail_code:"+238",code:"CV", flag: require('./assets/svgs/us.svg')},
{name:"Cayman Islands",dail_code:"+ 345",code:"KY", flag: require('./assets/svgs/us.svg')},
{name:"Central African Republic",dail_code:"+236",code:"CF", flag: require('./assets/svgs/us.svg')},
{name:"Chad",dail_code:"+235",code:"TD", flag: require('./assets/svgs/us.svg')},
{name:"Chile",dail_code:"+56",code:"CL", flag: require('./assets/svgs/us.svg')},
{name:"China",dail_code:"+86",code:"CN", flag: require('./assets/svgs/us.svg')},
{name:"Christmas Island",dail_code:"+61",code:"CX", flag: require('./assets/svgs/us.svg')},
{name:"Colombia",dail_code:"+57",code:"CO", flag: require('./assets/svgs/us.svg')},
{name:"Comoros",dail_code:"+269",code:"KM", flag: require('./assets/svgs/us.svg')},
{name:"Congo",dail_code:"+242",code:"CG", flag: require('./assets/svgs/us.svg')},
{name:"Cook Islands",dail_code:"+682",code:"CK", flag: require('./assets/svgs/us.svg')},
{name:"Costa Rica",dail_code:"+506",code:"CR", flag: require('./assets/svgs/us.svg')},
{name:"Croatia",dail_code:"+385",code:"HR", flag: require('./assets/svgs/us.svg')},
{name:"Cuba",dail_code:"+53",code:"CU", flag: require('./assets/svgs/us.svg')},
{name:"Cyprus",dail_code:"+537",code:"CY", flag: require('./assets/svgs/us.svg')},
{name:"Czech Republic",dail_code:"+420",code:"CZ", flag: require('./assets/svgs/us.svg')},
{name:"Denmark",dail_code:"+45",code:"DK", flag: require('./assets/svgs/us.svg')},
{name:"Djibouti",dail_code:"+253",code:"DJ", flag: require('./assets/svgs/us.svg')},
{name:"Dominica",dail_code:"+1 767",code:"DM", flag: require('./assets/svgs/us.svg')},
{name:"Dominican Republic",dail_code:"+1 849",code:"DO", flag: require('./assets/svgs/us.svg')},
{name:"Ecuador",dail_code:"+593",code:"EC", flag: require('./assets/svgs/us.svg')},
{name:"Egypt",dail_code:"+20",code:"EG", flag: require('./assets/svgs/us.svg')},
{name:"El Salvador",dail_code:"+503",code:"SV", flag: require('./assets/svgs/us.svg')},
{name:"Equatorial Guinea",dail_code:"+240",code:"GQ", flag: require('./assets/svgs/us.svg')},
{name:"Eritrea",dail_code:"+291",code:"ER", flag: require('./assets/svgs/us.svg')},
{name:"Estonia",dail_code:"+372",code:"EE", flag: require('./assets/svgs/us.svg')},
{name:"Ethiopia",dail_code:"+251",code:"ET", flag: require('./assets/svgs/us.svg')},
{name:"Faroe Islands",dail_code:"+298",code:"FO", flag: require('./assets/svgs/us.svg')},
{name:"Fiji",dail_code:"+679",code:"FJ", flag: require('./assets/svgs/us.svg')},
{name:"Finland",dail_code:"+358",code:"FI", flag: require('./assets/svgs/us.svg')},
{name:"France",dail_code:"+33",code:"FR", flag: require('./assets/svgs/us.svg')},
{name:"French Guiana",dail_code:"+594",code:"GF", flag: require('./assets/svgs/us.svg')},
{name:"French Polynesia",dail_code:"+689",code:"PF", flag: require('./assets/svgs/us.svg')},
{name:"Gabon",dail_code:"+241",code:"GA", flag: require('./assets/svgs/us.svg')},
{name:"Gambia",dail_code:"+220",code:"GM", flag: require('./assets/svgs/us.svg')},
{name:"Georgia",dail_code:"+995",code:"GE", flag: require('./assets/svgs/us.svg')},
{name:"Germany",dail_code:"+49",code:"DE", flag: require('./assets/svgs/us.svg')},
{name:"Ghana",dail_code:"+233",code:"GH", flag: require('./assets/svgs/us.svg')},
{name:"Gibraltar",dail_code:"+350",code:"GI", flag: require('./assets/svgs/us.svg')},
{name:"Greece",dail_code:"+30",code:"GR", flag: require('./assets/svgs/us.svg')},
{name:"Greenland",dail_code:"+299",code:"GL", flag: require('./assets/svgs/us.svg')},
{name:"Grenada",dail_code:"+1 473",code:"GD", flag: require('./assets/svgs/us.svg')},
{name:"Guadeloupe",dail_code:"+590",code:"GP", flag: require('./assets/svgs/us.svg')},
{name:"Guam",dail_code:"+1 671",code:"GU", flag: require('./assets/svgs/us.svg')},
{name:"Guatemala",dail_code:"+502",code:"GT", flag: require('./assets/svgs/us.svg')},
{name:"Guinea",dail_code:"+224",code:"GN", flag: require('./assets/svgs/us.svg')},
{name:"Guinea-Bissau",dail_code:"+245",code:"GW", flag: require('./assets/svgs/us.svg')},
{name:"Guyana",dail_code:"+595",code:"GY", flag: require('./assets/svgs/us.svg')},
{name:"Haiti",dail_code:"+509",code:"HT", flag: require('./assets/svgs/us.svg')},
{name:"Honduras",dail_code:"+504",code:"HN", flag: require('./assets/svgs/us.svg')},
{name:"Hungary",dail_code:"+36",code:"HU", flag: require('./assets/svgs/us.svg')},
{name:"Iceland",dail_code:"+354",code:"IS", flag: require('./assets/svgs/us.svg')},
{name:"India",dail_code:"+91",code:"IN", flag: require('./assets/svgs/us.svg')},
{name:"Indonesia",dail_code:"+62",code:"ID", flag: require('./assets/svgs/us.svg')},
{name:"Iraq",dail_code:"+964",code:"IQ", flag: require('./assets/svgs/us.svg')},
{name:"Ireland",dail_code:"+353",code:"IE", flag: require('./assets/svgs/us.svg')},
{name:"Israel",dail_code:"+972",code:"IL", flag: require('./assets/svgs/us.svg')},
{name:"Italy",dail_code:"+39",code:"IT", flag: require('./assets/svgs/us.svg')},
{name:"Jamaica",dail_code:"+1 876",code:"JM", flag: require('./assets/svgs/us.svg')},
{name:"Japan",dail_code:"+81",code:"JP", flag: require('./assets/svgs/us.svg')},
{name:"Jordan",dail_code:"+962",code:"JO", flag: require('./assets/svgs/us.svg')},
{name:"Kazakhstan",dail_code:"+7 7",code:"KZ", flag: require('./assets/svgs/us.svg')},
{name:"Kenya",dail_code:"+254",code:"KE", flag: require('./assets/svgs/us.svg')},
{name:"Kiribati",dail_code:"+686",code:"KI", flag: require('./assets/svgs/us.svg')},
{name:"Kuwait",dail_code:"+965",code:"KW", flag: require('./assets/svgs/us.svg')},
{name:"Kyrgyzstan",dail_code:"+996",code:"KG", flag: require('./assets/svgs/us.svg')},
{name:"Latvia",dail_code:"+371",code:"LV", flag: require('./assets/svgs/us.svg')},
{name:"Lebanon",dail_code:"+961",code:"LB", flag: require('./assets/svgs/us.svg')},
{name:"Lesotho",dail_code:"+266",code:"LS", flag: require('./assets/svgs/us.svg')},
{name:"Liberia",dail_code:"+231",code:"LR", flag: require('./assets/svgs/us.svg')},
{name:"Liechtenstein",dail_code:"+423",code:"LI", flag: require('./assets/svgs/us.svg')},
{name:"Lithuania",dail_code:"+370",code:"LT", flag: require('./assets/svgs/us.svg')},
{name:"Luxembourg",dail_code:"+352",code:"LU", flag: require('./assets/svgs/us.svg')},
{name:"Madagascar",dail_code:"+261",code:"MG", flag: require('./assets/svgs/us.svg')},
{name:"Malawi",dail_code:"+265",code:"MW", flag: require('./assets/svgs/us.svg')},
{name:"Malaysia",dail_code:"+60",code:"MY", flag: require('./assets/svgs/us.svg')},
{name:"Maldives",dail_code:"+960",code:"MV", flag: require('./assets/svgs/us.svg')},
{name:"Mali",dail_code:"+223",code:"ML", flag: require('./assets/svgs/us.svg')},
{name:"Malta",dail_code:"+356",code:"MT", flag: require('./assets/svgs/us.svg')},
{name:"Marshall Islands",dail_code:"+692",code:"MH", flag: require('./assets/svgs/us.svg')},
{name:"Martinique",dail_code:"+596",code:"MQ", flag: require('./assets/svgs/us.svg')},
{name:"Mauritania",dail_code:"+222",code:"MR", flag: require('./assets/svgs/us.svg')},
{name:"Mauritius",dail_code:"+230",code:"MU", flag: require('./assets/svgs/us.svg')},
{name:"Mayotte",dail_code:"+262",code:"YT", flag: require('./assets/svgs/us.svg')},
{name:"Mexico",dail_code:"+52",code:"MX", flag: require('./assets/svgs/us.svg')},
{name:"Monaco",dail_code:"+377",code:"MC", flag: require('./assets/svgs/us.svg')},
{name:"Mongolia",dail_code:"+976",code:"MN", flag: require('./assets/svgs/us.svg')},
{name:"Montenegro",dail_code:"+382",code:"ME", flag: require('./assets/svgs/us.svg')},
{name:"Montserrat",dail_code:"+1664",code:"MS", flag: require('./assets/svgs/us.svg')},
{name:"Morocco",dail_code:"+212",code:"MA", flag: require('./assets/svgs/us.svg')},
{name:"Myanmar",dail_code:"+95",code:"MM", flag: require('./assets/svgs/us.svg')},
{name:"Namibia",dail_code:"+264",code:"NA", flag: require('./assets/svgs/us.svg')},
{name:"Nauru",dail_code:"+674",code:"NR", flag: require('./assets/svgs/us.svg')},
{name:"Nepal",dail_code:"+977",code:"NP", flag: require('./assets/svgs/us.svg')},
{name:"Netherlands",dail_code:"+31",code:"NL", flag: require('./assets/svgs/us.svg')},
// {name:"Netherlands Antilles",dail_code:"+599",code:"AN", flag: require('./assets/svgs/us.svg')},
{name:"New Caledonia",dail_code:"+687",code:"NC", flag: require('./assets/svgs/us.svg')},
{name:"New Zealand",dail_code:"+64",code:"NZ", flag: require('./assets/svgs/us.svg')},
{name:"Nicaragua",dail_code:"+505",code:"NI", flag: require('./assets/svgs/us.svg')},
{name:"Niger",dail_code:"+227",code:"NE", flag: require('./assets/svgs/us.svg')},
{name:"Nigeria",dail_code:"+234",code:"NG", flag: require('./assets/svgs/us.svg')},
{name:"Niue",dail_code:"+683",code:"NU", flag: require('./assets/svgs/us.svg')},
{name:"Norfolk Island",dail_code:"+672",code:"NF", flag: require('./assets/svgs/us.svg')},
{name:"Northern Mariana Islands",dail_code:"+1 670",code:"MP", flag: require('./assets/svgs/us.svg')},
{name:"Norway",dail_code:"+47",code:"NO", flag: require('./assets/svgs/us.svg')},
{name:"Oman",dail_code:"+968",code:"OM", flag: require('./assets/svgs/us.svg')},
{name:"Pakistan",dail_code:"+92",code:"PK", flag: require('./assets/svgs/us.svg')},
{name:"Palau",dail_code:"+680",code:"PW", flag: require('./assets/svgs/us.svg')},
{name:"Panama",dail_code:"+507",code:"PA", flag: require('./assets/svgs/us.svg')},
{name:"Papua New Guinea",dail_code:"+675",code:"PG", flag: require('./assets/svgs/us.svg')},
{name:"Paraguay",dail_code:"+595",code:"PY", flag: require('./assets/svgs/us.svg')},
{name:"Peru",dail_code:"+51",code:"PE", flag: require('./assets/svgs/us.svg')},
{name:"Philippines",dail_code:"+63",code:"PH", flag: require('./assets/svgs/us.svg')},
{name:"Poland",dail_code:"+48",code:"PL", flag: require('./assets/svgs/us.svg')},
{name:"Portugal",dail_code:"+351",code:"PT", flag: require('./assets/svgs/us.svg')},
{name:"Puerto Rico",dail_code:"+1 939",code:"PR", flag: require('./assets/svgs/us.svg')},
{name:"Qatar",dail_code:"+974",code:"QA", flag: require('./assets/svgs/us.svg')},
{name:"Romania",dail_code:"+40",code:"RO", flag: require('./assets/svgs/us.svg')},
{name:"Rwanda",dail_code:"+250",code:"RW", flag: require('./assets/svgs/us.svg')},
{name:"Samoa",dail_code:"+685",code:"WS", flag: require('./assets/svgs/us.svg')},
{name:"San Marino",dail_code:"+378",code:"SM", flag: require('./assets/svgs/us.svg')},
{name:"Saudi Arabia",dail_code:"+966",code:"SA", flag: require('./assets/svgs/us.svg')},
{name:"Senegal",dail_code:"+221",code:"SN", flag: require('./assets/svgs/us.svg')},
{name:"Serbia",dail_code:"+381",code:"RS", flag: require('./assets/svgs/us.svg')},
{name:"Seychelles",dail_code:"+248",code:"SC", flag: require('./assets/svgs/us.svg')},
{name:"Sierra Leone",dail_code:"+232",code:"SL", flag: require('./assets/svgs/us.svg')},
{name:"Singapore",dail_code:"+65",code:"SG", flag: require('./assets/svgs/us.svg')},
{name:"Slovakia",dail_code:"+421",code:"SK", flag: require('./assets/svgs/us.svg')},
{name:"Slovenia",dail_code:"+386",code:"SI", flag: require('./assets/svgs/us.svg')},
{name:"Solomon Islands",dail_code:"+677",code:"SB", flag: require('./assets/svgs/us.svg')},
{name:"South Africa",dail_code:"+27",code:"ZA", flag: require('./assets/svgs/us.svg')},
{name:"South Georgia and the South Sandwich Islands",dail_code:"+500",code:"GS", flag: require('./assets/svgs/us.svg')},
{name:"Spain",dail_code:"+34",code:"ES", flag: require('./assets/svgs/us.svg')},
{name:"Sri Lanka",dail_code:"+94",code:"LK", flag: require('./assets/svgs/us.svg')},
{name:"Sudan",dail_code:"+249",code:"SD", flag: require('./assets/svgs/us.svg')},
{name:"Suriname",dail_code:"+597",code:"SR", flag: require('./assets/svgs/us.svg')},
{name:"Swaziland",dail_code:"+268",code:"SZ", flag: require('./assets/svgs/us.svg')},
{name:"Sweden",dail_code:"+46",code:"SE", flag: require('./assets/svgs/us.svg')},
{name:"Switzerland",dail_code:"+41",code:"CH", flag: require('./assets/svgs/us.svg')},
{name:"Tajikistan",dail_code:"+992",code:"TJ", flag: require('./assets/svgs/us.svg')},
{name:"Thailand",dail_code:"+66",code:"TH", flag: require('./assets/svgs/us.svg')},
{name:"Togo",dail_code:"+228",code:"TG", flag: require('./assets/svgs/us.svg')},
{name:"Tokelau",dail_code:"+690",code:"TK", flag: require('./assets/svgs/us.svg')},
{name:"Tonga",dail_code:"+676",code:"TO", flag: require('./assets/svgs/us.svg')},
{name:"Trinidad and Tobago",dail_code:"+1 868",code:"TT", flag: require('./assets/svgs/us.svg')},
{name:"Tunisia",dail_code:"+216",code:"TN", flag: require('./assets/svgs/us.svg')},
{name:"Turkey",dail_code:"+90",code:"TR", flag: require('./assets/svgs/us.svg')},
{name:"Turkmenistan",dail_code:"+993",code:"TM", flag: require('./assets/svgs/us.svg')},
{name:"Turks and Caicos Islands",dail_code:"+1 649",code:"TC", flag: require('./assets/svgs/us.svg')},
{name:"Tuvalu",dail_code:"+688",code:"TV", flag: require('./assets/svgs/us.svg')},
{name:"Uganda",dail_code:"+256",code:"UG", flag: require('./assets/svgs/us.svg')},
{name:"Ukraine",dail_code:"+380",code:"UA", flag: require('./assets/svgs/us.svg')},
{name:"United Arab Emirates",dail_code:"+971",code:"AE", flag: require('./assets/svgs/us.svg')},
{name:"United Kingdom",dail_code:"+44",code:"GB", flag: require('./assets/svgs/us.svg')},
{name:"United States",dail_code:"+1",code:"US", flag: require('./assets/svgs/us.svg')},
{name:"Uruguay",dail_code:"+598",code:"UY", flag: require('./assets/svgs/us.svg')},

{name:"Uzbekistan",dail_code:"+998",code:"UZ", flag: require('./assets/svgs/us.svg')},
{name:"Vanuatu",dail_code:"+678",code:"VU", flag: require('./assets/svgs/us.svg')},
{name:"Wallis and Futuna",dail_code:"+681",code:"WF", flag: require('./assets/svgs/us.svg')},
{name:"Yemen",dail_code:"+967",code:"YE", flag: require('./assets/svgs/us.svg')},
{name:"Zambia",dail_code:"+260",code:"ZM", flag: require('./assets/svgs/us.svg')},
{name:"Zimbabwe",dail_code:"+263",code:"ZW", flag: require('./assets/svgs/us.svg')},
{name:"land Islands",dail_code:"",code:"AX", flag: require('./assets/svgs/us.svg')},
{name:"Antarctica",dail_code:null,code:"AQ", flag: require('./assets/svgs/us.svg')},
{name:"Bolivia, Plurinational State of",dail_code:"+591",code:"BO", flag: require('./assets/svgs/us.svg')},
{name:"Brunei Darussalam",dail_code:"+673",code:"BN", flag: require('./assets/svgs/us.svg')},
{name:"Cocos (Keeling) Islands",dail_code:"+61",code:"CC", flag: require('./assets/svgs/us.svg')},
{name:"Congo, The Democratic Republic of the",dail_code:"+243",code:"CD", flag: require('./assets/svgs/us.svg')},
{name:"Cote d'Ivoire",dail_code:"+225",code:"CI", flag: require('./assets/svgs/us.svg')},
{name:"Falkland Islands (Malvinas)",dail_code:"+500",code:"FK", flag: require('./assets/svgs/us.svg')},
{name:"Guernsey",dail_code:"+44",code:"GG", flag: require('./assets/svgs/us.svg')},
{name:"Holy See (Vatican City State)",dail_code:"+379",code:"VA", flag: require('./assets/svgs/us.svg')},
{name:"Hong Kong",dail_code:"+852",code:"HK", flag: require('./assets/svgs/us.svg')},
{name:"Iran, Islamic Republic of",dail_code:"+98",code:"IR", flag: require('./assets/svgs/us.svg')},
{name:"Isle of Man",dail_code:"+44",code:"IM", flag: require('./assets/svgs/us.svg')},
{name:"Jersey",dail_code:"+44",code:"JE", flag: require('./assets/svgs/us.svg')},
{name:"Korea, Democratic People's Republic of",dail_code:"+850",code:"KP", flag: require('./assets/svgs/us.svg')},
{name:"Korea, Republic of",dail_code:"+82",code:"KR", flag: require('./assets/svgs/us.svg')},
{name:"Lao People's Democratic Republic",dail_code:"+856",code:"LA", flag: require('./assets/svgs/us.svg')},
{name:"Libyan Arab Jamahiriya",dail_code:"+218",code:"LY", flag: require('./assets/svgs/us.svg')},
{name:"Macao",dail_code:"+853",code:"MO", flag: require('./assets/svgs/us.svg')},
{name:"Macedonia, The Former Yugoslav Republic of",dail_code:"+389",code:"MK", flag: require('./assets/svgs/us.svg')},
{name:"Micronesia, Federated States of",dail_code:"+691",code:"FM", flag: require('./assets/svgs/us.svg')},
{name:"Moldova, Republic of",dail_code:"+373",code:"MD", flag: require('./assets/svgs/us.svg')},
{name:"Mozambique",dail_code:"+258",code:"MZ", flag: require('./assets/svgs/us.svg')},
{name:"Palestinian Territory, Occupied",dail_code:"+970",code:"PS", flag: require('./assets/svgs/us.svg')},
{name:"Pitcairn",dail_code:"+872",code:"PN", flag: require('./assets/svgs/us.svg')},
{name:"Réunion",dail_code:"+262",code:"RE", flag: require('./assets/svgs/us.svg')},
{name:"Russia",dail_code:"+7",code:"RU", flag: require('./assets/svgs/us.svg')},
{name:"Saint Barthélemy",dail_code:"+590",code:"BL", flag: require('./assets/svgs/us.svg')},
{name:"Saint Helena, Ascension and Tristan Da Cunha",dail_code:"+290",code:"SH", flag: require('./assets/svgs/us.svg')},
{name:"Saint Kitts and Nevis",dail_code:"+1 869",code:"KN", flag: require('./assets/svgs/us.svg')},
{name:"Saint Lucia",dail_code:"+1 758",code:"LC", flag: require('./assets/svgs/us.svg')},
{name:"Saint Martin",dail_code:"+590",code:"MF", flag: require('./assets/svgs/us.svg')},
{name:"Saint Pierre and Miquelon",dail_code:"+508",code:"PM", flag: require('./assets/svgs/us.svg')},
{name:"Saint Vincent and the Grenadines",dail_code:"+1 784",code:"VC", flag: require('./assets/svgs/us.svg')},
{name:"Sao Tome and Principe",dail_code:"+239",code:"ST", flag: require('./assets/svgs/us.svg')},
{name:"Somalia",dail_code:"+252",code:"SO", flag: require('./assets/svgs/us.svg')},
{name:"Svalbard and Jan Mayen",dail_code:"+47",code:"SJ", flag: require('./assets/svgs/us.svg')},
{name:"Syrian Arab Republic",dail_code:"+963",code:"SY", flag: require('./assets/svgs/us.svg')},
{name:"Taiwan, Province of China",dail_code:"+886",code:"TW", flag: require('./assets/svgs/us.svg')},
{name:"Tanzania, United Republic of",dail_code:"+255",code:"TZ", flag: require('./assets/svgs/us.svg')},
{name:"Timor-Leste",dail_code:"+670",code:"TL", flag: require('./assets/svgs/us.svg')},
{name:"Venezuela, Bolivarian Republic of",dail_code:"+58",code:"VE", flag: require('./assets/svgs/us.svg')},
{name:"Viet Nam",dail_code:"+84",code:"VN", flag: require('./assets/svgs/us.svg')},
{name:"Virgin Islands, British",dail_code:"+1 284",code:"VG", flag: require('./assets/svgs/us.svg')},
{name:"Virgin Islands, U.S.",dail_code:"+1 340",code:"VI"}]
export default data;